export type ClassroomSlide={
  section:string;
  title:string;
  lead:string;
  points?:string[];
  callout?:string;
  prompt?:string;
  layout?:"title"|"statement"|"split"|"steps"|"exercise";
};

export const asteronDeck:ClassroomSlide[]=[
  {section:"SKILLS4SALES · ASTERON MOBILITY",title:"Sales ownership begins where the lead handover ends",lead:"A connected learning journey from initial interest to an earned customer commitment.",callout:"Lead Generation → Sales Ownership → Customer Movement",layout:"title"},
  {section:"OPENING PULSE",title:"A lead is not yet an opportunity",lead:"Lead generation creates attention and identifies possible interest. Sales creates informed movement by accepting responsibility for what happens next.",points:["Interest tells us where to look.","Discovery tells us whether change matters.","Commitment tells us whether the opportunity is moving."],prompt:"At what moment do you personally begin to own the customer outcome?",layout:"statement"},
  {section:"CUSTOMER LIFECYCLE",title:"Ownership must continue across the whole customer journey",lead:"A salesperson does not merely carry a lead to a proposal. Ownership means protecting continuity from first conversation through value realisation and growth.",points:["Prospect — establish relevance","Qualified lead — clarify why now","Discovery — understand impact and people","Solution — connect value to priorities","Decision — earn a credible commitment","Onboarding and growth — sustain the promised outcome"],callout:"The customer experiences one journey—even when your organisation uses many teams.",layout:"steps"},
  {section:"SALES OWNERSHIP",title:"Ownership is visible in the next movement you create",lead:"The strongest salesperson knows what the customer needs to understand, decide or do next—and takes responsibility for making that movement useful.",points:["Prepare before contacting","Clarify the business trigger","Map the people involved","Make the next commitment explicit"],callout:"Ownership is not doing everything yourself. It is ensuring that nothing important becomes ownerless.",layout:"split"},
  {section:"THE CUSTOMER SITUATION",title:"Asteron’s request is only the visible tip of the opportunity",lead:"Asteron Mobility operates 11 plants and is onboarding two EV customers. Priya Nair, VP Operations, has requested an automation overview after downloading a paper.",points:["Known: scale, growth pressure, interest in automation","Unknown: business trigger, cost of delay, buying group, decision path","Risk: responding to the request without understanding the situation"],prompt:"What would you need to learn before showing a capability deck?",layout:"exercise"},
  {section:"RAPPORT",title:"Rapport is earned through relevance—not extended small talk",lead:"Customers experience rapport when the salesperson demonstrates preparation, attention and respect for their reality.",points:["Open with a relevant reason for the conversation.","Use the customer’s language before introducing your own.","Show that you heard what matters by following up on significant words."],callout:"Rapport creates permission to explore—not permission to pitch.",layout:"split"},
  {section:"QUESTIONING",title:"Good discovery moves from situation to consequence",lead:"Questions should form a purposeful sequence. Each answer should help you decide what to explore next.",points:["Situation — What is happening today?","Friction — Where does the current approach break down?","Impact — What does that affect commercially or operationally?","Priority — Why does it matter now?","Movement — Who must be involved and what should happen next?"],prompt:"Which question would reveal why Asteron cannot leave the situation unchanged?",layout:"steps"},
  {section:"BUSINESS COMMUNICATION",title:"Listen, link and use language the customer can act on",lead:"A clear conversation connects what the customer said to why it matters, without hiding behind technical detail.",points:["Listen for facts, emotions, constraints and significant words.","Link the issue to an operational or commercial consequence.","Use plain language and confirm shared understanding."],callout:"Clarity is not simplification for its own sake. It is making the decision easier to think about.",layout:"split"},
  {section:"PAIN POINTS",title:"A symptom becomes a pain point when its consequence is understood",lead:"‘Release coordination is difficult’ describes friction. Discovery becomes commercially meaningful when we uncover what that friction delays, increases, threatens or prevents.",points:["Symptom: repeated coordination","Operational effect: slower release cycles","Business consequence: delayed customer onboarding and revenue","Personal consequence: reduced confidence in transformation"],prompt:"What evidence would help you test this hypothesis with Priya?",layout:"statement"},
  {section:"STAKEHOLDER MAPPING",title:"The opportunity moves only when the buying group can move",lead:"Different stakeholders judge the same change through different success and risk criteria.",points:["Priya · Sponsor — operational speed and adoption","Dev · CIO — stability, integration and disruption","Meera · Plant Head — reliability and usability","Omar · Finance — measurable return and risk","Procurement · Process — commercial and governance fit"],callout:"Map influence, interest, success criteria and likely resistance—not just job titles.",layout:"steps"},
  {section:"BUYING SIGNALS",title:"A signal shows willingness to invest attention, access or action",lead:"Questions about capability are not always buying signals. Stronger signals involve internal participation, feasibility, timing or a concrete next step.",points:["Information: ‘Can you send an overview?’","Interest: ‘Have you done this in a similar environment?’","Movement: ‘Who should join a discovery workshop?’","Commitment: ‘Can we reserve time next week with Operations and IT?’"],prompt:"Which signal would justify asking for a workshop commitment?",layout:"split"},
  {section:"UNDERSTANDING THE BUSINESS",title:"Business acumen begins with how the customer creates value",lead:"Before describing a solution, understand how Asteron wins, what the operating model must deliver and where performance is constrained.",points:["Strategic priority — EV customer growth","Operating requirement — dependable, faster releases","Constraint — fragmented routines and 14 hand-offs","Stake — onboarding dates, service reliability and confidence","Measure — time, disruption, risk and speed to value"],callout:"Technology becomes valuable only when it changes an outcome the business cares about.",layout:"steps"},
  {section:"VALUE CONVERSATIONS",title:"Value connects a customer problem to a meaningful outcome",lead:"A value conversation is a shared explanation of why change matters—not a list of product advantages.",points:["Because you are experiencing…","It is affecting…","We can help you achieve…","By changing…","While reducing…"],callout:"For Asteron: connect release friction to onboarding speed, operational reliability and transformation risk.",layout:"statement"},
  {section:"APPLICATION",title:"Build the first eight minutes of the Asteron conversation",lead:"Your goal is not to complete discovery. It is to establish relevance, understand the business trigger and earn the next layer of conversation.",points:["Open with a relevant point of view.","Ask one situation question and two consequence questions.","Follow up on one significant word.","Avoid premature solutioning.","Secure a credible next commitment."],prompt:"What will the customer understand or reveal by minute eight?",layout:"exercise"},
  {section:"ROLE-PLAY TRIAD",title:"Three roles create three different learning lenses",lead:"The salesperson practises; the customer protects private context; the observer watches for evidence of effective behaviour.",points:["A · Salesperson — advance understanding without pitching","B · Customer — reveal information only when the conversation earns it","C · Observer — capture evidence, not general impressions"],callout:"Rotate roles so every learner experiences all three perspectives.",layout:"steps"},
  {section:"CASE LAB",title:"The strongest next step is the one the customer is ready to own",lead:"Asteron asks about governance, references, a 90-day pathway and who should attend a workshop. These questions suggest the customer is testing feasibility and internal movement.",points:["Summarise the business situation in customer language.","Confirm the success and risk criteria that remain unknown.","Propose a workshop with the right stakeholders and a clear purpose."],prompt:"What exact commitment would you ask Priya to make?",layout:"exercise"},
  {section:"LEARNING TRANSFER",title:"The demo ends when workplace application begins",lead:"Capture one shift in how you think, one behaviour you will practise and one customer opportunity where you will apply it.",points:["My key takeaway","The behaviour I will change","The opportunity where I will apply it","The support or feedback I need"],callout:"Sales ownership is sustained through deliberate practice, reflection and feedback.",layout:"statement"},
];

export const asteronDeckDownload="/downloads/asteron-mobility-sales-transition.pptx";
