"use client";
import { useEffect,useMemo,useState } from "react";
type Entry={topic:string;entry:string;updated_at?:string};
const topics=["Sales ownership","Opportunity preparation","Discovery","Role-play practice","Value conversation","Learning transfer"];
export default function LearnerJournal({open,onClose,topic,prompt,learnerName,sessionName}:{open:boolean;onClose:()=>void;topic:string;prompt:string;learnerName:string;sessionName:string}){
  const [entries,setEntries]=useState<Entry[]>([]);const [selected,setSelected]=useState(topic||topics[0]);const [text,setText]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>{if(open)load()},[open]);useEffect(()=>{if(topic){setSelected(topic);const found=entries.find(e=>e.topic===topic);setText(found?.entry||prompt||"")}},[topic,prompt,open]);
  async function load(){const r=await fetch("/api/journal");const d=await r.json() as {entries?:Entry[]};const list=d.entries??[];setEntries(list);const target=topic||selected;setText(list.find(e=>e.topic===target)?.entry||prompt||"")}
  function choose(value:string){setSelected(value);setText(entries.find(e=>e.topic===value)?.entry||"");setMessage("")}
  async function save(){setMessage("Saving…");const r=await fetch("/api/journal",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({topic:selected,entry:text})});if(r.ok){setMessage("Journal entry saved ✓");await load()}else setMessage("Could not save this entry.")}
  const shareText=useMemo(()=>`Skills4Sales Learning Journal\n${sessionName}\n${selected}\n\n${text}\n\n— ${learnerName}`,[selected,text,sessionName,learnerName]);
  async function share(){if(navigator.share)await navigator.share({title:`Skills4Sales Journal — ${selected}`,text:shareText});else location.href=`mailto:?subject=${encodeURIComponent(`Skills4Sales Journal — ${selected}`)}&body=${encodeURIComponent(shareText)}`}
  if(!open)return null;return <div className="journal-backdrop"><section className="journal-drawer" role="dialog" aria-modal="true" aria-label="Learning journal"><header><div><span>MY LEARNING JOURNAL</span><h2>Pause. Capture. Carry forward.</h2><p>{sessionName} · {learnerName}</p></div><button onClick={onClose} aria-label="Close journal">×</button></header><div className="journal-fields"><label>Journal topic<select value={selected} onChange={e=>choose(e.target.value)}>{topics.map(t=><option key={t}>{t}</option>)}</select></label>{prompt&&<blockquote>{prompt}</blockquote>}<label>My reflection<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Capture what you noticed, what it means and what you will do…"/></label>{message&&<p className="journal-message">{message}</p>}</div><footer><button className="journal-save" disabled={!text.trim()} onClick={save}>Save journal</button><button onClick={()=>window.print()}>Download / print PDF</button><button onClick={()=>location.href=`mailto:?subject=${encodeURIComponent(`Skills4Sales Journal — ${selected}`)}&body=${encodeURIComponent(shareText)}`}>Email</button><button onClick={share}>Share to device apps</button></footer></section></div>
}
