"use client";

import { useEffect,useMemo,useState } from "react";
import type { CSSProperties } from "react";
import LearningReading from "./learning-reading";
import LearnerJournal from "./learner-journal";
import SessionDeck from "./session-deck";

type Step="pulse"|"workbook"|"cards"|"roleplay"|"case"|"finish";
type Role="salesperson"|"customer"|"observer";
type Brief={title:string;copy:string;task:string};
type TriadState={code:string;round:number;baseRole:Role|null;role:Role|null;brief:Brief|null;available:Role[];unavailable:Role[];memberCount:number;timerRunning:boolean;timerEndsAt:number|null;timerRemaining:number;active:boolean};
type SessionState={code:string;name:string;activities:Record<Step,boolean>;presentation:{open:boolean;slide:number};debrief:{activity:string;response:unknown}|null};
const steps:{id:Step;label:string;verb:string}[]=[
  {id:"pulse",label:"Live Pulse",verb:"Locate yourself"},{id:"workbook",label:"Workbook",verb:"Own the opportunity"},{id:"cards",label:"Discovery Cards",verb:"Read the customer"},{id:"roleplay",label:"Role Play",verb:"Practise the meeting"},{id:"case",label:"Case Lab",verb:"Build the value"},{id:"finish",label:"Reflection",verb:"Close the demo"},
];
const roleLabels:Record<Role,string>={salesperson:"Role A · Salesperson",customer:"Role B · Customer",observer:"Role C · Observer"};
const cards=[
  {type:"PAIN",prompt:"Priya says, ‘Every release creates a fresh round of coordination.’ What business consequence may sit underneath this?",lens:"Move from the visible symptom—coordination—to delay, cost, risk and customer impact."},
  {type:"PEOPLE",prompt:"Who must be involved before this opportunity can move beyond an exploratory conversation?",lens:"Map the business sponsor, technical evaluator, operational users, finance and procurement—then identify each person’s concern."},
  {type:"SIGNAL",prompt:"Priya asks whether a discovery workshop could include plant operations and IT. Is this a buying signal? Why?",lens:"Yes. She is testing an internal next step and widening stakeholder participation—stronger than a general request for information."},
  {type:"QUESTION",prompt:"What question would reveal why this matters now rather than six months from now?",lens:"Ask about the business change, deadline or consequence that has made the status quo unacceptable now."},
  {type:"BUSINESS",prompt:"Asteron is onboarding two EV customers. How could release friction affect that business priority?",lens:"Connect technology delay with onboarding dates, service reliability, contractual confidence and speed to revenue."},
  {type:"WILD CARD",prompt:"Write the question Priya should have been asked—but has not yet heard.",lens:"The best question advances understanding without smuggling in a pitch."},
];
const caseLayers=[
  {title:"The inherited lead",text:"Asteron Mobility downloaded an automation paper and requested an overview. Marketing marked the lead qualified.",question:"What does sales ownership require first?",options:["Send a capability deck","Clarify why Asteron engaged now","Ask for the technical specification"],answer:1},
  {title:"The operating reality",text:"Eleven plants use different release routines. Customer-portal changes take six weeks and involve fourteen hand-offs.",question:"Which discovery direction creates the most value?",options:["List automation features","Explore delay, disruption and business impact","Confirm the available budget"],answer:1},
  {title:"The buying group",text:"Priya sponsors the conversation. CIO Dev is wary of disruption; Plant Head Meera wants reliability; Finance Director Omar wants measurable return.",question:"What should the next meeting accomplish?",options:["Win Priya’s approval alone","Give every stakeholder the same pitch","Surface each stakeholder’s success and risk criteria"],answer:2},
  {title:"Signals of movement",text:"Priya asks about governance, references, a 90-day pathway and who should attend a workshop.",question:"What is the strongest interpretation?",options:["She is only gathering information","She is testing feasibility and internal movement","She is ready to sign immediately"],answer:1},
];

export default function SalesTransitionLab({learnerName}:{learnerName:string}){
  const [step,setStep]=useState<Step>("pulse");const [done,setDone]=useState<Step[]>([]);const [saving,setSaving]=useState("");
  const [pulse,setPulse]=useState({owner:"",confidence:"3",handoff:""});const [pulseSubmitted,setPulseSubmitted]=useState(false);
  const [workbook,setWorkbook]=useState({ownedBefore:"",ownNow:"",unknowns:"",stakeholders:"",signals:""});
  const [cardIndex,setCardIndex]=useState(0);const [cardAnswer,setCardAnswer]=useState("");const [cardHistory,setCardHistory]=useState<string[]>([]);const [reveal,setReveal]=useState(false);const [deckComplete,setDeckComplete]=useState(false);
  const [triadCode,setTriadCode]=useState("");const [triad,setTriad]=useState<TriadState|null>(null);const [triadMessage,setTriadMessage]=useState("");const [roleNotes,setRoleNotes]=useState("");const [roleComplete,setRoleComplete]=useState(false);const [submittedRound,setSubmittedRound]=useState(0);const [now,setNow]=useState(Date.now());
  const [caseIndex,setCaseIndex]=useState(0);const [caseChoices,setCaseChoices]=useState<number[]>([]);const [value,setValue]=useState("");const [nextStep,setNextStep]=useState("");const [caseComplete,setCaseComplete]=useState(false);
  const [feedback,setFeedback]=useState({takeaway:"",rating:"5",comment:""});const [feedbackComplete,setFeedbackComplete]=useState(false);
  const [sessionState,setSessionState]=useState<SessionState>({code:"WEDNESDAY-DEMO",name:"Wednesday Client Demo",activities:{pulse:true,workbook:true,cards:true,roleplay:true,case:true,finish:true},presentation:{open:true,slide:0},debrief:null});
  const [theme,setTheme]=useState<"light"|"dark">("light");const [fontScale,setFontScale]=useState(1);const [settingsOpen,setSettingsOpen]=useState(false);const [focus,setFocus]=useState(false);const [journalOpen,setJournalOpen]=useState(false);const [journalTopic,setJournalTopic]=useState("Sales ownership");const [journalPrompt,setJournalPrompt]=useState("");
  const [deckOpen,setDeckOpen]=useState(false);
  const progress=Math.round(done.filter(x=>x!=="finish").length/5*100);const caseScore=useMemo(()=>caseChoices.reduce((sum,choice,i)=>sum+(choice===caseLayers[i]?.answer?1:0),0),[caseChoices]);
  useEffect(()=>{restore();refreshSession();const clock=setInterval(()=>setNow(Date.now()),1000);const statePoll=setInterval(refreshSession,3000);return()=>{clearInterval(clock);clearInterval(statePoll)}},[]);
  useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("s4s_preferences")||"{}");if(p.theme==="dark")setTheme("dark");if(Number(p.fontScale))setFontScale(Number(p.fontScale))}catch{}},[]);
  useEffect(()=>{if(!triad?.role)return;const id=setInterval(()=>checkTriad(undefined,true),2000);return()=>clearInterval(id)},[triad?.code,triad?.role,triad?.round,submittedRound]);
  async function save(activity:string,response:unknown,score?:number,mark?:Step){setSaving("Saving…");try{const r=await fetch("/api/responses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({activity,response,score})});if(!r.ok)throw new Error();if(activity==="roleplay"&&response&&typeof response==="object"&&"round" in response)setSubmittedRound(Number((response as {round:number}).round));if(mark)setDone(d=>d.includes(mark)?d:[...d,mark]);setSaving("Response captured ✓");return true}catch{setSaving("Could not save. Please try again.");return false}}
  async function checkTriad(role?:Role,silent=false,codeOverride?:string){if(!silent)setTriadMessage("Checking triad…");const code=codeOverride??triadCode;const r=await fetch("/api/triads/join",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,role})});const d=await r.json() as TriadState&{error?:string};if(d.code){if((triad?.round&&d.round!==triad.round)||(submittedRound&&d.round!==submittedRound)){setRoleComplete(false);setRoleNotes("")}setTriadCode(d.code);setTriad(d)}if(!silent)setTriadMessage(d.error??(d.role?`${roleLabels[d.role]} assigned to you. Private brief unlocked.`:"Triad found. Choose one available role."));}
  async function refreshSession(){const r=await fetch("/api/session-state");if(r.ok){const d=await r.json() as {session:SessionState};setSessionState(d.session)}}
  async function restore(){const r=await fetch("/api/progress");if(!r.ok)return;const d=await r.json() as {progress:Record<string,{response:any;score:number|null}>};const p=d.progress;const completed=Object.keys(p).filter(k=>k!=="roleplay"||Number(p[k].response?.round)===3).map(k=>k==="feedback"?"finish":k).filter(k=>steps.some(s=>s.id===k)) as Step[];setDone([...new Set(completed)]);if(p.pulse){setPulse(p.pulse.response);setPulseSubmitted(true)}if(p.workbook)setWorkbook(p.workbook.response);if(p.cards){setCardHistory(p.cards.response);setDeckComplete(true)}if(p.roleplay){const x=p.roleplay.response;setRoleNotes(x.notes??"");setSubmittedRound(Number(x.round)||1);setRoleComplete(true);if(x.triad){setTriadCode(x.triad);await checkTriad(undefined,true,x.triad)}}if(p.case){setCaseChoices(p.case.response.choices??[]);setValue(p.case.response.value??"");setNextStep(p.case.response.nextStep??"");setCaseIndex(caseLayers.length);setCaseComplete(true)}if(p.feedback){setFeedback(p.feedback.response);setFeedbackComplete(true)}}
  function chooseCase(choice:number){const next=[...caseChoices];next[caseIndex]=choice;setCaseChoices(next)}
  function caseFeedback(layer:number,choice:number){const right=caseLayers[layer]?.answer===choice;return {pros:right?"Addresses the customer situation before pitching and creates a stronger basis for movement.":"Keeps the conversation moving, but may leave important business context, stakeholders or urgency unexplored.",cons:right?"Requires disciplined discovery before presenting a solution.":"Risks premature solutioning or a weak next step without enough customer evidence."}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
  function preference(nextTheme=theme,nextScale=fontScale){setTheme(nextTheme);setFontScale(nextScale);localStorage.setItem("s4s_preferences",JSON.stringify({theme:nextTheme,fontScale:nextScale}))}
  function openJournal(prompt=""){const labels:Record<Step,string>={pulse:"Sales ownership",workbook:"Opportunity preparation",cards:"Discovery",roleplay:"Role-play practice",case:"Value conversation",finish:"Learning transfer"};setJournalTopic(labels[step]);setJournalPrompt(prompt);setJournalOpen(true)}
  const isOpen=sessionState.activities[step]!==false;const triadSeconds=triad?.timerRunning&&triad.timerEndsAt?Math.max(0,Math.ceil((triad.timerEndsAt-now)/1000)):triad?.timerRemaining??480;
  return <main className={`transition-lab learner-${theme} ${focus?"learner-focus":""}`} style={{"--learner-scale":fontScale} as CSSProperties}><header className="lab-top"><a className="brand" href="/"><img className="brand-logo" src="/s4s-logo.png" alt="S4S Skills4Sales"/><span><strong>Skills4Sales</strong><small>SALES TRANSITION LAB</small></span></a><div><span>{learnerName}</span><button disabled={!sessionState.presentation.open} onClick={()=>setDeckOpen(true)}>{sessionState.presentation.open?"Class Deck":"Deck locked"}</button><button onClick={()=>openJournal()}>Journal</button><button onClick={()=>setFocus(true)}>Focus</button><button onClick={()=>setSettingsOpen(!settingsOpen)}>Settings</button><button onClick={logout}>Exit</button></div></header>
    {focus&&<button className="focus-exit" onClick={()=>setFocus(false)}>Exit focus mode ×</button>}
    {settingsOpen&&<section className="learner-settings"><div><b>Display settings</b><span>Saved on this device</span></div><label>Theme<button className={theme==="light"?"active":""} onClick={()=>preference("light",fontScale)}>Light</button><button className={theme==="dark"?"active":""} onClick={()=>preference("dark",fontScale)}>Dark</button></label><label>Text size<button onClick={()=>preference(theme,Math.max(.8,Number((fontScale-.1).toFixed(1))))}>A−</button><strong>{Math.round(fontScale*100)}%</strong><button onClick={()=>preference(theme,Math.min(1.4,Number((fontScale+.1).toFixed(1))))}>A+</button></label><button onClick={()=>setSettingsOpen(false)}>Close</button></section>}
    <section className="opportunity-strip"><div><p>{sessionState.name.toUpperCase()}</p><h1>Asteron Mobility</h1></div><p>One qualified lead. Five connected learning moves. Your goal is to turn initial interest into an earned customer commitment.</p><b>{progress}% complete</b></section>
    <div className="lab-layout"><aside className="lab-rail"><p className="eyebrow">JOURNEY MAP</p>{steps.map((s,i)=>{const locked=!sessionState.activities[s.id]||(s.id==="finish"&&!caseComplete);return <button key={s.id} disabled={locked} onClick={()=>setStep(s.id)} className={step===s.id?"active":""}><span>{done.includes(s.id)?"✓":String(i+1).padStart(2,"0")}</span><b>{s.label}<small>{!sessionState.activities[s.id]?"Locked by facilitator":s.id==="finish"&&!caseComplete?"Complete Case Lab first":s.verb}</small></b></button>})}</aside>
      <section className="lab-workspace">
        {!isOpen&&<div className="activity-locked"><span>⌁</span><h2>This activity is currently locked.</h2><p>Your facilitator will release it when the session is ready to continue.</p></div>}
        {isOpen&&<>
        <LearningReading key={step} step={step} onJournal={openJournal}/>
        {step==="pulse"&&<div className="activity-panel"><ActivityHead no="01" tag="LIVE PULSE" title="When does a lead become yours?" copy="Take a position before the customer story unfolds. Your responses become the starting point for the debrief."/><div className="pulse-grid"><label>After qualification, who owns movement?<select value={pulse.owner} disabled={pulseSubmitted} onChange={e=>setPulse({...pulse,owner:e.target.value})}><option value="">Choose</option><option>Lead generation</option><option>Sales</option><option>Shared—without a named owner</option></select></label><label>Confidence in a first customer conversation<span className="range-value">{pulse.confidence}/5</span><input type="range" min="1" max="5" disabled={pulseSubmitted} value={pulse.confidence} onChange={e=>setPulse({...pulse,confidence:e.target.value})}/></label><label className="wide">Where do you most often hand responsibility back?<textarea disabled={pulseSubmitted} value={pulse.handoff} onChange={e=>setPulse({...pulse,handoff:e.target.value})} placeholder="Name a moment in the customer lifecycle…"/></label></div>{!pulseSubmitted&&<ActionButton disabled={!pulse.owner||!pulse.handoff.trim()} onClick={async()=>{if(await save("pulse",pulse,undefined,"pulse"))setPulseSubmitted(true)}} text="Submit to the live pulse"/>}{pulseSubmitted&&<div className={`learning-feedback ${pulse.owner==="Sales"?"correct":"better"}`}><b>{pulse.owner==="Sales"?"Best answer":"A better answer"}</b><p><strong>Sales owns movement after qualification.</strong> Lead generation supports continuity, but the salesperson becomes accountable for understanding the customer, advancing the opportunity and securing the next commitment.</p></div>}</div>}
        {step==="workbook"&&<div className="activity-panel"><ActivityHead no="02" tag="DIGITAL WORKBOOK" title="From inherited lead to owned opportunity" copy="Marketing has handed over Asteron Mobility. Priya Nair, VP Operations, requested an automation overview after downloading a paper."/><div className="customer-facts"><div className="facts-row"><b>KNOWN</b><span>11 plants</span><span>EV customer growth</span><span>Automation interest</span></div><div className="facts-row"><b>UNKNOWN</b><span>Business trigger</span><span>Buying group</span><span>Cost of inaction</span></div></div><div className="workbook-grid"><Prompt label="What did lead generation own?" value={workbook.ownedBefore} set={v=>setWorkbook({...workbook,ownedBefore:v})}/><Prompt label="What must sales own now?" value={workbook.ownNow} set={v=>setWorkbook({...workbook,ownNow:v})}/><Prompt label="What must you discover?" value={workbook.unknowns} set={v=>setWorkbook({...workbook,unknowns:v})}/><Prompt label="Who may influence the decision?" value={workbook.stakeholders} set={v=>setWorkbook({...workbook,stakeholders:v})}/><Prompt label="Which buying signals will you watch for?" value={workbook.signals} set={v=>setWorkbook({...workbook,signals:v})}/></div><ActionButton disabled={Object.values(workbook).some(v=>!v.trim())} onClick={()=>save("workbook",workbook,undefined,"workbook")} text={done.includes("workbook")?"Workbook saved ✓":"Save workbook page"}/></div>}
        {step==="cards"&&<div className="activity-panel"><ActivityHead no="03" tag="DISCOVERY CARD GAME" title="Signal or Noise?" copy="Each card exposes another angle of the same Asteron opportunity. Respond before revealing the coach’s lens."/>{deckComplete?<Completion title="Deck completed!" copy="All six discovery responses have been captured for the facilitator debrief." action="Continue to Role Play" onClick={()=>setStep("roleplay")}/>:<div className="card-stage"><div className="game-card"><span>{cards[cardIndex].type}</span><small>CARD {cardIndex+1} OF {cards.length}</small><h2>{cards[cardIndex].prompt}</h2><textarea value={cardAnswer} onChange={e=>setCardAnswer(e.target.value)} placeholder="Capture your response…"/><button onClick={()=>setReveal(true)} disabled={!cardAnswer.trim()}>Reveal coach’s lens</button>{reveal&&<p><b>COACH’S LENS</b>{cards[cardIndex].lens}</p>}</div><aside><b>YOUR DECK</b><div className="mini-cards">{cards.map((c,i)=><button key={c.type} className={i===cardIndex?"active":""} onClick={()=>{setCardIndex(i);setCardAnswer(cardHistory[i]||"");setReveal(false)}}>{i+1}<small>{c.type}</small>{i<cardHistory.length&&<b aria-label="Completed">✓</b>}</button>)}</div><button className="next-card" disabled={!reveal} onClick={async()=>{const h=[...cardHistory];h[cardIndex]=cardAnswer;setCardHistory(h);if(cardIndex<cards.length-1){setCardIndex(cardIndex+1);setCardAnswer(h[cardIndex+1]||"");setReveal(false)}else if(await save("cards",h,undefined,"cards"))setDeckComplete(true)}}>{cardIndex===cards.length-1?"Complete the deck":"Next card →"}</button></aside></div>}</div>}
        {step==="roleplay"&&<div className="activity-panel"><ActivityHead no="04" tag="ROLE-PLAY LAB" title="The first eight minutes" copy="Enter the code generated by your facilitator. All three learners share the same round and timer; each rotation unlocks a new private role."/>{roleComplete?<Completion title={`Round ${triad?.round??1} response submitted!`} copy={triad?.round===3?"You have completed all three role perspectives.":"Wait for the facilitator to rotate the triad. Your next private role will unlock automatically."} action={triad?.round===3?"Continue to Case Lab":"Refresh triad status"} onClick={()=>triad?.round===3?setStep("case"):checkTriad(undefined,true)}/>:!triad?.role?<div className="triad-join"><label>TRIAD CODE<input value={triadCode} maxLength={6} onChange={e=>{setTriadCode(e.target.value.toUpperCase());setTriad(null)}} placeholder="Enter 6-character code"/></label><button disabled={triadCode.length<6} onClick={()=>checkTriad()}>Find my triad</button>{triadMessage&&<p>{triadMessage}</p>}{triad&&<div className="role-claim"><b>AVAILABLE ROLES</b>{(["salesperson","customer","observer"] as Role[]).map(role=><button key={role} disabled={triad.unavailable.includes(role)} onClick={()=>checkTriad(role)}>{roleLabels[role]}<small>{triad.unavailable.includes(role)?"Already assigned":"Available"}</small></button>)}</div>}</div>:<><div className="triad-status"><span>TRIAD {triad.code} · ROUND {triad.round}</span><b>{roleLabels[triad.role]}</b><small>{triad.memberCount}/3 joined · Role and timer synchronised by facilitator</small></div><div className="role-timer"><strong>{String(Math.floor(triadSeconds/60)).padStart(2,"0")}:{String(triadSeconds%60).padStart(2,"0")}</strong><span>{triad.timerRunning?"Round in progress":"Waiting for facilitator"}</span></div><div className="role-brief"><span>PRIVATE ROLE BRIEF · ROUND {triad.round}</span><h2>{triad.brief?.title}</h2><p>{triad.brief?.copy}</p><b>{triad.brief?.task}</b></div><label className="role-capture">Capture your preparation or feedback<textarea value={roleNotes} onChange={e=>setRoleNotes(e.target.value)} placeholder="Write here…"/></label><ActionButton disabled={!roleNotes.trim()} onClick={async()=>{if(await save("roleplay",{triad:triad.code,round:triad.round,role:triad.role,notes:roleNotes},undefined,triad.round===3?"roleplay":undefined))setRoleComplete(true)}} text={`Submit round ${triad.round} capture`}/></>}</div>}
        {step==="case"&&<div className="activity-panel"><ActivityHead no="05" tag="PROGRESSIVE CASE" title="The opportunity behind the request" copy="Integrate the full journey. Each decision unlocks the next layer of Asteron’s customer story."/>{caseComplete?<Completion title="Sales Transition Lab completed!" copy="Your decisions, value statement and proposed next commitment have been captured." action="Continue to takeaways & feedback" onClick={()=>setStep("finish")}/>:<><div className="case-progress">{caseLayers.map((l,i)=><span key={l.title} className={i<caseChoices.length?"done":i===caseIndex?"active":""}>{i+1}</span>)}</div>{caseIndex<caseLayers.length&&<div className="case-layer"><span>LAYER {caseIndex+1}</span><h2>{caseLayers[caseIndex].title}</h2><p>{caseLayers[caseIndex].text}</p><h3>{caseLayers[caseIndex].question}</h3>{caseLayers[caseIndex].options.map((o,i)=><button key={o} className={caseChoices[caseIndex]===i?"selected":""} onClick={()=>chooseCase(i)}>{String.fromCharCode(65+i)}. {o}</button>)}{caseChoices[caseIndex]!==undefined&&<div className="case-coaching"><b>COACHING LENS</b><p><strong>What this choice can do:</strong> {caseFeedback(caseIndex,caseChoices[caseIndex]).pros}</p><p><strong>Trade-off to consider:</strong> {caseFeedback(caseIndex,caseChoices[caseIndex]).cons}</p></div>}<button className="case-next" disabled={caseChoices[caseIndex]===undefined} onClick={()=>setCaseIndex(caseIndex+1)}>{caseIndex===caseLayers.length-1?"Build the value conversation":"Continue to next layer →"}</button></div>}{caseIndex===caseLayers.length&&<div className="value-builder"><p className="score-chip">DECISIONS: {caseScore}/{caseLayers.length}</p><h2>Earn the next commitment</h2><label>Customer-centred value statement<textarea value={value} onChange={e=>setValue(e.target.value)} placeholder="Because Asteron is experiencing…, it is affecting…. We can help…"/></label><label>Credible next commitment<textarea value={nextStep} onChange={e=>setNextStep(e.target.value)} placeholder="Who should do what, by when—and why?"/></label><ActionButton disabled={!value.trim()||!nextStep.trim()} onClick={async()=>{if(await save("case",{choices:caseChoices,value,nextStep},caseScore,"case"))setCaseComplete(true)}} text="Complete the Sales Transition Lab"/></div>}</>}</div>}
        {step==="finish"&&<div className="activity-panel finish-panel"><ActivityHead no="06" tag="DEMO CLOSE" title="The demo experience ends here." copy="Before you leave, capture what mattered most and help us improve the learning experience."/>{!feedbackComplete?<><div className="feedback-form"><label>My key takeaway<textarea value={feedback.takeaway} onChange={e=>setFeedback({...feedback,takeaway:e.target.value})} placeholder="What will you carry into your next customer conversation?"/></label><label>How useful was this experience?<select value={feedback.rating} onChange={e=>setFeedback({...feedback,rating:e.target.value})}><option value="5">5 — Highly useful</option><option value="4">4 — Useful</option><option value="3">3 — Moderately useful</option><option value="2">2 — Limited usefulness</option><option value="1">1 — Not useful yet</option></select></label><label>Feedback or suggestion<textarea value={feedback.comment} onChange={e=>setFeedback({...feedback,comment:e.target.value})} placeholder="What should we retain, change or add?"/></label></div><ActionButton disabled={!feedback.takeaway.trim()||!feedback.comment.trim()} onClick={async()=>{if(await save("feedback",feedback,Number(feedback.rating),"finish"))setFeedbackComplete(true)}} text="Submit takeaways & feedback"/></>:<div className="logout-card"><span>✓</span><h2>Thank you, {learnerName}.</h2><p>Your takeaway and feedback have been captured. Please log out to close your learner session securely.</p><button onClick={logout}>Log out of Skills4Sales →</button></div>}</div>}
        </>}
        {saving&&<p className="save-status" role="status">{saving}</p>}
        {sessionState.debrief&&<div className="learner-debrief"><span>FACILITATOR DEBRIEF · {sessionState.debrief.activity.toUpperCase()}</span><h3>Response selected for discussion</h3><p>{debriefText(sessionState.debrief.response)}</p></div>}
      </section></div><SessionDeck open={deckOpen&&sessionState.presentation.open} current={sessionState.presentation.slide} onClose={()=>setDeckOpen(false)}/><LearnerJournal open={journalOpen} onClose={()=>setJournalOpen(false)} topic={journalTopic} prompt={journalPrompt} learnerName={learnerName} sessionName={sessionState.name}/></main>
}

function ActivityHead({no,tag,title,copy}:{no:string;tag:string;title:string;copy:string}){return <header className="activity-head"><span>{no}</span><div><p className="eyebrow">{tag}</p><h1>{title}</h1><p>{copy}</p></div></header>}
function Prompt({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label>{label}<textarea value={value} onChange={e=>set(e.target.value)} placeholder="Capture your thinking…"/></label>}
function ActionButton({disabled,onClick,text}:{disabled:boolean;onClick:()=>void|Promise<void>;text:string}){return <button className="activity-submit" disabled={disabled} onClick={onClick}>{text} <span>→</span></button>}
function Completion({title,copy,action,onClick}:{title:string;copy:string;action:string;onClick:()=>void}){return <div className="completion-card"><span>✓</span><h2>{title}</h2><p>{copy}</p><button onClick={onClick}>{action} →</button></div>}
function debriefText(value:unknown){if(Array.isArray(value))return value.filter(Boolean).slice(0,3).join(" · ");if(value&&typeof value==="object")return Object.values(value).flat().filter(v=>typeof v==="string"&&v.trim()).slice(0,3).join(" · ");return String(value??"")}
