"use client";
import { useEffect,useMemo,useState } from "react";
type ResponseRow={id:number;learnerName:string;activity:string;response:string;score:number|null;createdAt:string};
const labels:Record<string,string>={pulse:"Live Pulse",workbook:"Workbook",cards:"Discovery Cards",roleplay:"Role Play",case:"Case Lab",feedback:"Takeaways & Feedback"};
export default function FacilitatorResponses({sessionCode}:{sessionCode:string}){
  const [rows,setRows]=useState<ResponseRow[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState("all");const [selected,setSelected]=useState<number|null>(null);const [projected,setProjected]=useState<number|null>(null);
  async function load(){setLoading(true);try{const r=await fetch(`/api/responses?sessionCode=${encodeURIComponent(sessionCode)}`);const d=await r.json() as {responses?:ResponseRow[]};setRows(d.responses||[])}finally{setLoading(false)}}
  useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[sessionCode]);
  const visible=filter==="all"?rows:rows.filter(r=>r.activity===filter);const pulse=useMemo(()=>pulseSummary(rows),[rows]);
  async function project(id:number|null){await fetch("/api/sessions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sessionCode,debriefResponseId:id,debriefVisible:id!==null})});setProjected(id)}
  async function clearLearnerInputs(){if(!confirm("Clear all learner responses for this session? This cannot be undone."))return;await fetch(`/api/responses?sessionCode=${encodeURIComponent(sessionCode)}`,{method:"DELETE"});setSelected(null);setProjected(null);await load()}
  return <section className="response-console"><div className="response-head"><div><p className="eyebrow">LIVE DEBRIEF CONSOLE</p><h2>Incoming learner evidence</h2><p>Aggregate the pulse, highlight a response for discussion, or project it anonymously to every learner.</p></div><div><button onClick={load}>{loading?"Refreshing…":"Refresh responses ↻"}</button><button onClick={clearLearnerInputs}>Clear demo learner inputs</button></div></div>
    <div className="pulse-summary"><article><span>RESPONSES</span><strong>{pulse.total}</strong></article><article><span>SALES OWNS MOVEMENT</span><strong>{pulse.sales}</strong></article><article><span>AVERAGE CONFIDENCE</span><strong>{pulse.average}/5</strong></article><article><span>FEEDBACK AVERAGE</span><strong>{pulse.feedback}/5</strong></article></div>
    <div className="response-filters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All <b>{rows.length}</b></button>{Object.keys(labels).map(k=><button key={k} className={filter===k?"active":""} onClick={()=>setFilter(k)}>{labels[k]} <b>{rows.filter(r=>r.activity===k).length}</b></button>)}</div>
    <button className="hide-projection" disabled={!projected} onClick={()=>project(null)}>Stop showing response</button>
    {visible.length===0?<div className="empty-responses"><b>No responses yet</b><p>Submissions will appear here as learners complete each activity.</p></div>:<div className="response-list">{visible.map(row=><article key={row.id} className={selected===row.id?"highlighted":""}><div><span>{labels[row.activity]||row.activity}</span><b>{row.learnerName}</b><small>{row.createdAt}</small></div><p>{summary(row.response)}</p>{row.score!==null&&<strong>{row.score}/{row.activity==="feedback"?5:4}</strong>}<nav><button onClick={()=>setSelected(selected===row.id?null:row.id)}>{selected===row.id?"Unhighlight":"Highlight"}</button><button onClick={()=>project(row.id)}>{projected===row.id?"Showing now":"Show to learners"}</button></nav></article>)}</div>}
  </section>
}
function parsed(raw:string){try{return JSON.parse(raw)}catch{return raw}}
function summary(raw:string){const value=parsed(raw);if(Array.isArray(value))return value.filter(Boolean).slice(0,2).join(" · ")||"Activity completed";if(typeof value==="object"&&value){const parts=Object.values(value).flat().filter(v=>typeof v==="string"&&v.trim());return parts.slice(0,3).join(" · ")||"Response captured"}return String(value)}
function pulseSummary(rows:ResponseRow[]){const latest=new Map<string,ResponseRow>();for(const r of rows)if(!latest.has(`${r.learnerName}:${r.activity}`))latest.set(`${r.learnerName}:${r.activity}`,r);const pulse=[...latest.values()].filter(r=>r.activity==="pulse");const data=pulse.map(r=>parsed(r.response) as {owner?:string;confidence?:string});const feedback=[...latest.values()].filter(r=>r.activity==="feedback"&&r.score!==null);return{total:new Set(rows.map(r=>r.learnerName)).size,sales:data.filter(x=>x.owner==="Sales").length,average:data.length?(data.reduce((s,x)=>s+Number(x.confidence||0),0)/data.length).toFixed(1):"0.0",feedback:feedback.length?(feedback.reduce((s,x)=>s+Number(x.score),0)/feedback.length).toFixed(1):"0.0"}}
