"use client";
import { useEffect,useState } from "react";
type Triad={id:number;code:string;active:boolean;created_at:string;round:number;timer_running:boolean;timer_remaining:number;timer_ends_at:number|null;member_count:number};
export default function TriadManager({sessionCode}:{sessionCode:string}){
  const [triads,setTriads]=useState<Triad[]>([]);const [message,setMessage]=useState("");const [,tick]=useState(0);
  async function load(){const r=await fetch(`/api/triads?sessionCode=${encodeURIComponent(sessionCode)}`);const d=await r.json() as {triads?:Triad[]};setTriads(d.triads??[])}
  useEffect(()=>{load();const id=setInterval(()=>{load();tick(x=>x+1)},2000);return()=>clearInterval(id)},[sessionCode]);
  async function create(){setMessage("Generating…");const r=await fetch("/api/triads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionCode})});const d=await r.json() as {triad?:Triad;error?:string};if(d.triad){setMessage(`Triad ${d.triad.code} is ready`);await load()}else setMessage(d.error??"Could not generate a code.")}
  async function act(code:string,action:string){if(action==="delete"){if(!confirm(`Delete triad ${code}?`))return;await fetch(`/api/triads?code=${encodeURIComponent(code)}`,{method:"DELETE"})}else await fetch("/api/triads",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({code,action})});await load()}
  function remaining(t:Triad){return t.timer_running&&t.timer_ends_at?Math.max(0,Math.ceil((Number(t.timer_ends_at)-Date.now())/1000)):Number(t.timer_remaining)||480}
  return <section className="triad-manager"><div><p className="eyebrow">SYNCHRONISED ROLE-PLAY TRIADS</p><h2>Generate and control triads</h2><p>All three devices share the same round and timer. Advancing a round rotates every learner to a new private role.</p><button onClick={create}>Generate triad code +</button>{message&&<span>{message}</span>}</div><aside className="triad-control-list">{triads.length===0?<p>No triads generated for this session.</p>:triads.map(t=>{const sec=remaining(t);return <article key={t.id}><div><strong>{t.code}</strong><span>Round {t.round} · {t.member_count}/3 joined</span><small>{String(Math.floor(sec/60)).padStart(2,"0")}:{String(sec%60).padStart(2,"0")}</small></div><nav><button onClick={()=>act(t.code,t.timer_running?"pause":"start")}>{t.timer_running?"Pause":"Start"}</button><button onClick={()=>act(t.code,"reset")}>Reset</button><button onClick={()=>act(t.code,"next")}>Rotate roles</button><button onClick={()=>act(t.code,"close")}>Close</button></nav></article>})}</aside></section>
}
